### ISSUE TITLE
Rule with Event based on >= watt values 

### ISSUE THREAD

**Issue by santiagos5** [hardez/homebridge-senec#2]
Hello, thanks for your work!

in Eve app i can’t create rule based on event with “>= xxx watt” maybe because are shown as outlet. last year i had solaredge inverter and plugin was shown ad lux sensor (not watt) so i created event based on >= lux.

do you think is it possibile in future show as lux sensor the actual solar production? Or do you know a way on Eve app to create event (not condition) based on >= ?

**Comment by JoMensdorf** [comment]
Hi!
Have the same question, I´d like to set up an automation if there is a surplus of power to turn on the heater.

Thanks!!!

**Comment by hardez** [comment]
I've got in contact with the Eve devs, but they don't see the need to implement this feature for actors represented in watt.

You can use the app Home+
There you can do exactly that. I switch to that app by myself.
