### ISSUE TITLE
HTTP not working anymore, SENEC switched to HTTPS

### ISSUE THREAD

**Issue by jens-vonberg** [hardez/homebridge-senec#3]
SENEC pushed a firmware update to the V2.1 machines and since then HTTP has been disabled in favor if HTTPS. The API still seems to be working fine when testing with postman and ignoring certificate errors.

Could you update your code to HTTPS?

Thanks for you great work by the way. I am using this to make automations with homekit.

Sorry, hier ist alles auf Deutsch. Deshalb nochmal:
SENEC hat mit dem Firmware-Update, welches seit letzter Woche gepusht wird auf HTTPS umgestellt. Mit Postman und HTTPS scheint alles zu funktionieren.

Kannst du bitte dein Plugin auf HTTPS umstellen? Ich liebe das Plugin und benutze es für diverse Automationen mit Homekit.

Danke im Voraus.

**Comment by hardez** [comment]
hab das Update veröffentlicht, sollte jetzt auch über den Homebridge-Updater verfügbar sein

**Comment by jens-vonberg** [comment]
Danke
